### PR TITLE
Minimum trade changes

### PR DESCRIPTION
**Pull request by Flexz9**

### CODE REVIEW

**Comment by Flexz9** [comment]
ETP_USD("ETP", "USD", 4.0),
  	ETP_BTC("ETP", "BTC", 4.0),
  	ETP_ETH("ETP", "ETH", 4.0),
 -	
 -	// Qtum
  	QTM_USD("QTM", "USD", 0.4),
  	QTM_BTC("QTM", "BTC", 0.4),
  	QTM_ETH("QTM", "ETH", 0.4),

They are still in there.
I'm using https://api.bitfinex.com/v1/symbols_details
Their open api from V1 that includes every pair they have.

It should be a complete list.

**Comment by jnidzwetzki** [comment]
Hi,

You're right, the symbols are all still included. I apologize for my erroneous comment. Your PR adds 22 lines and removes 83 lines. All comments like '// Bitcoin' or '// Etherium' are removed by the PR. Is this intended?

**Comment by Flexz9** [comment]
I was lazy to group them and add these lines, because I auto generated the code based on the JSON with Javascript, but maybe it would be a good idea to update these values on startup of the bot.
Using the public API call. Then future updates to edit or add coins is not needed anymore.

**Comment by jnidzwetzki** [comment]
Thanks for your work!

**Pull request merged**
