### PR TITLE
AccountInfoHandler: not handled "hb" on channel 0 even if not authenticated - fix

### PR DESCRIPTION
**Pull request by mironbalcerzak**
Hi Jan,
Apparently bitfinex exchange was sending "hb" event on 0 channel, even if user is not authenticated. That was causing issues, especially in PooledBitfinexApiBroker.

Here's a fix for that case.
We will need to release new version to maven central sadly 👎 sorry about that.

--- Miron

### CODE REVIEW

**Comment by mironbalcerzak** [comment]
Ive updated CHANGELOG.md as per request

**Comment by jnidzwetzki** [comment]
It seems the PR introduces a problem in the integration test. I have re-run the test several times but with your proposed change, the integration test fails always with:

`
10:25:11.333 [47] ERROR c.g.j.b.v.SimpleBitfinexApiBroker - Got exception while reconnect
com.github.jnidzwetzki.bitfinex.v2.exception.BitfinexClientException: Subscription of ticker failed: got only 1 of 2 symbols subscribed
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.handleResubscribeFailed(SimpleBitfinexApiBroker.java:651) ~[classes/:?]
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.waitForChannelResubscription(SimpleBitfinexApiBroker.java:620) ~[classes/:?]
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.resubscribeChannels(SimpleBitfinexApiBroker.java:599) ~[classes/:?]
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.reconnect(SimpleBitfinexApiBroker.java:413) [classes/:?]
	at com.github.jnidzwetzki.bitfinex.v2.test.integration.IntegrationTest.testReconnect(IntegrationTest.java:374) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292) [junit-4.12.jar:4.12]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
` 

Currently I don't have much time, could you take a look at this?

**Comment by mironbalcerzak** [comment]
Sure thing, let me see what happens there

**Comment by mironbalcerzak** [comment]
I'm pretty sure I've run all tests last night and all was fine. I will address the failing tests, as I'm having them locally broken too.

**Comment by jnidzwetzki** [comment]
I was able to reproduce the problem locally. The problem is that the following code:

`
bitfinexClient.unsubscribeAllChannels();
Assert.assertTrue(bitfinexClient.getSubscribedChannels().isEmpty());
`

does not work anymore. We still have one subscribed channel (id 0) after we call `unsubscribeAllChannels`. In addition, the reconnect method fails, because the number of subscribed channels does not match. 

Until now, this problem only occurs on authenticated channels. With proposed change, the problem also occurs on unauthenticated channels. Because the main issue is already in the code, I will merge the PR. But we have to solve the problem before we release the next version.

**Comment by mironbalcerzak** [comment]
No worries - I will address this shortly - in next PR i will provide a fix for that

**Pull request merged**
